import {
  black,
  blue,
  brown,
  cream,
  gajri,
  gray,
  green,
  mehendi,
  metal,
  orange,
  pink,
  purple,
  red,
  white,
  yellow,
} from "../CommonComponent/Colors";

export const colors = [
  { data: red, key: "red" },
  { data: blue, key: "blue" },
  { data: cream, key: "cream" },
  { data: green, key: "green" },
  { data: yellow, key: "yellow" },
  { data: gray, key: "gray" },
  { data: white, key: "white" },
  { data: black, key: "black" },
  { data: mehendi, key: "mehendi" },
  { data: brown, key: "brown" },
  { data: metal, key: "metal" },
  { data: purple, key: "purple" },
  { data: orange, key: "orange" },
  { data: gajri, key: "gajri" },
  { data: pink, key: "pink" },
];
