export const Colors = [
  { code: ["#0000FF"], color: "Royal Blue" },
  { code: ["#38B0DE"], color: "Sky Blue" },
  { code: ["#1575BF"], color: "Denim" },
  { code: ["#213E9E"], color: "Persian Blue" },
  { code: ["#01447F"], color: "Prussian Blue" },
  { code: ["#129CB7"], color: "Iris Blue" },
  { code: ["#191970"], color: "Midnight Blue" },
  { code: ["#353B5B"], color: "Gulf Blue" },
  { code: ["#9bc3eb"], color: "Light Sky Blue" },
  // { code: ["#89C4FF"], color: "" },
  { code: ["#FF0000"], color: "Red" },
  { code: ["#9D0C2B"], color: "Maroon" },
  { code: ["#9A0C29"], color: "Carmine" },
  { code: ["#843138"], color: "Old Brick" },
  { code: ["#00FF00"], color: "Parrot Green" },
  { code: ["#259797"], color: "Sea Green" },
  { code: ["#1AB385"], color: "Light Green" },
  { code: ["#166032"], color: "Crusoe" },
  { code: ["#4F7C33"], color: "Green Leaf" },
  { code: ["#218268"], color: "Elf Green" },
  { code: ["#66F4C3"], color: "Aquamarine" },
  { code: ["#167E65"], color: "Deep Sea" },
  { code: ["#1F881F"], color: "Spring Green" },
  { code: ["#1B4B35"], color: "Country Green" },
  { code: ["#A4EA9D"], color: "Granny Smith Apple" },
  { code: ["#C9E589"], color: "Sulu" },
  { code: ["#166461"], color: "Blue Stone" },
  { code: ["#80A084"], color: "Envy" },
  { code: ["#75A87A"], color: "Oxley" },
  { code: ["#FFFF00"], color: "Lemon" },
  { code: ["#FFEEA3"], color: "Cream Brulee" },
  { code: ["#FFC768"], color: "Grandis" },
  { code: ["#DAC01A"], color: "Sunflower" },
  { code: ["#FFFF99"], color: "Canary" },
  { code: ["#FFD67B"], color: "Salomie" },
  { code: ["#FF5900"], color: "Dark Orange" },
  { code: ["#FF8C00"], color: "Light Orange" },
  { code: ["#FFFFFF"], color: "White" },
  { code: ["#F4EFE0"], color: "Bianca" },
  { code: ["#E30B5C"], color: "Pink" },
  { code: ["#F4869A"], color: "Wewak" },
  { code: ["#AA3365"], color: "Lipstick" },
  { code: ["#FFC1E4"], color: "Cotton Candy" },
  { code: ["#CD526C"], color: "Cabaret" },
  { code: ["#D671AC"], color: "Pale Violet Red" },
  { code: ["#FFA38C"], color: "Mona Lisa" },
  { code: ["#F7AFBF"], color: "Cupid" },
  { code: ["#BF5D7A"], color: "Royal Heath" },
  { code: ["#B23971"], color: "Rouge" },
  { code: ["#DE3163"], color: "Cerise" },
  { code: ["#E54D5C"], color: "Gajri" },
  { code: ["#C45655"], color: "Fuzzy Wuzzy Brown" },
  { code: ["#E56D75"], color: "Froly" },
  { code: ["#FEAB9A"], color: "Rose Bud" },
  { code: ["#821762"], color: "Dark Purple" },
  { code: ["#A42AAA"], color: "Dark Orchid" },
  { code: ["#AD0082"], color: "Egg Plant" },
  { code: ["#88078E"], color: "Dark Violet Purple" },
  { code: ["#6A1F44"], color: "Pampadour" },
  { code: ["#633477"], color: "Kingfisher Daisy" },
  { code: ["#372D52"], color: "Cherry Pie" },
  { code: ["#492293"], color: "Persian Indigo" },
  { code: ["#6A4DAF"], color: "Blue Marquerite" },
  { code: ["#361556"], color: "Christalle" },
  { code: ["#4B2D72"], color: "Blue Diamond" },
  { code: ["#FFFDD0"], color: "Wheat" },
  { code: ["#DBB985"], color: "Raven Gold " },
  { code: ["#FCFAE0"], color: "Early Dawn" },
  { code: ["#F1F1C6"], color: "Spring Sun" },
  { code: ["#EFD8B6"], color: "Champagne" },
  { code: ["#CCB388"], color: "Straw" },
  { code: ["#FFF1C6"], color: "Blanched Almond" },
  { code: ["#6D7A86"], color: "Slate Grey" },
  { code: ["#2E526D"], color: "Blumine" },
  { code: ["#5D1F1E"], color: "Coke" },
  { code: ["#7F4534"], color: "Peanut" },
  { code: ["#8E4D3E"], color: "Mule Fawn" },
  { code: ["#74823D"], color: "Wasabi" },
  { code: ["#7C673A"], color: "Shingle Fawn" },
  { code: ["#63532C"], color: "Dallas" },
  { code: ["#75602C"], color: "Himalaya" },
  { code: ["#545429"], color: "Saragota" },
  { code: ["#636D24"], color: "Fizi Green" },
  { code: ["#C97A30"], color: "Bronze" },
  { code: ["#DAB160"], color: "Equator" },
  { code: ["#C69371"], color: "Fallow" },
  { code: ["#D37F5B"], color: "Burning Sand" },
  { code: ["#CE7259"], color: "Japonica" },
  { code: ["#000000"], color: "Black" },
  { code: ["#190000"], color: "Eclipse" },
];

export const blue = [
  { code: ["#0000FF"], color: "Royal Blue" },
  { code: ["#38B0DE"], color: "Sky Blue" },
  { code: ["#1575BF"], color: "Denim" },
  { code: ["#213E9E"], color: "Persian Blue" },
  { code: ["#01447F"], color: "Prussian Blue" },
  { code: ["#129CB7"], color: "Iris Blue" },
  { code: ["#191970"], color: "Midnight Blue" },
  { code: ["#353B5B"], color: "Gulf Blue" },
  { code: ["#9bc3eb"], color: "Light Sky Blue" },
];
export const red = [
  { code: ["#FF0000"], color: "Red" },
  { code: ["#9D0C2B"], color: "Maroon" },
  { code: ["#9A0C29"], color: "Carmine" },
  { code: ["#843138"], color: "Old Brick" },
];
export const green = [
  { code: ["#00FF00"], color: "Parrot Green" },
  { code: ["#259797"], color: "Sea Green" },
  { code: ["#1AB385"], color: "Light Green" },
  { code: ["#166032"], color: "Crusoe" },
  { code: ["#4F7C33"], color: "Green Leaf" },
  { code: ["#218268"], color: "Elf Green" },
  { code: ["#66F4C3"], color: "Aquamarine" },
  { code: ["#167E65"], color: "Deep Sea" },
  { code: ["#1F881F"], color: "Spring Green" },
  { code: ["#1B4B35"], color: "Country Green" },
  { code: ["#A4EA9D"], color: "Granny Smith Apple" },
  { code: ["#C9E589"], color: "Sulu" },
  { code: ["#166461"], color: "Blue Stone" },
  { code: ["#80A084"], color: "Envy" },
  { code: ["#75A87A"], color: "Oxley" },
];

export const yellow = [
  { code: ["#FFFF00"], color: "Lemon" },
  { code: ["#FFEEA3"], color: "Cream Brulee" },
  { code: ["#FFC768"], color: "Grandis" },
  { code: ["#DAC01A"], color: "Sunflower" },
  { code: ["#FFFF99"], color: "Canary" },
  { code: ["#FFD67B"], color: "Salomie" },
];
export const orange = [
  { code: ["#FF5900"], color: "Dark Orange" },
  { code: ["#FF8C00"], color: "Light Orange" },
];
export const white = [
  { code: ["#FFFFFF"], color: "White" },
  { code: ["#F4EFE0"], color: "Bianca" },
];

export const pink = [
  { code: ["#E30B5C"], color: "Pink" },
  { code: ["#F4869A"], color: "Wewak" },
  { code: ["#AA3365"], color: "Lipstick" },
  { code: ["#FFC1E4"], color: "Cotton Candy" },
  { code: ["#CD526C"], color: "Cabaret" },
  { code: ["#D671AC"], color: "Pale Violet Red" },
  { code: ["#FFA38C"], color: "Mona Lisa" },
  { code: ["#F7AFBF"], color: "Cupid" },
  { code: ["#BF5D7A"], color: "Royal Heath" },
  { code: ["#B23971"], color: "Rouge" },
  { code: ["#DE3163"], color: "Cerise" },
];

export const gajri = [
  { code: ["#E54D5C"], color: "Gajri" },
  { code: ["#C45655"], color: "Fuzzy Wuzzy Brown" },
  { code: ["#E56D75"], color: "Froly" },
  { code: ["#FEAB9A"], color: "Rose Bud" },
];

export const purple = [
  { code: ["#821762"], color: "Dark Purple" },
  { code: ["#A42AAA"], color: "Dark Orchid" },
  { code: ["#AD0082"], color: "Egg Plant" },
  { code: ["#88078E"], color: "Dark Violet Purple" },
  { code: ["#6A1F44"], color: "Pampadour" },
  { code: ["#633477"], color: "Kingfisher Daisy" },
  { code: ["#372D52"], color: "Cherry Pie" },
  { code: ["#492293"], color: "Persian Indigo" },
  { code: ["#6A4DAF"], color: "Blue Marquerite" },
  { code: ["#361556"], color: "Christalle" },
  { code: ["#4B2D72"], color: "Blue Diamond" },
];

export const cream = [
  { code: ["#DBB985"], color: "Raven Gold " },
  { code: ["#FCFAE0"], color: "Early Dawn" },
  { code: ["#F1F1C6"], color: "Spring Sun" },
  { code: ["#EFD8B6"], color: "Champagne" },
  { code: ["#CCB388"], color: "Straw" },
  { code: ["#FFF1C6"], color: "Blanched Almond" },
];

export const grey = [
  { code: ["#6D7A86"], color: "Slate Grey" },
  { code: ["#2E526D"], color: "Blumine" },
];

export const brown = [
  { code: ["#5D1F1E"], color: "Coke" },
  { code: ["#7F4534"], color: "Peanut" },
  { code: ["#8E4D3E"], color: "Mule Fawn" },
];

export const mehendi = [
  { code: ["#74823D"], color: "Wasabi" },
  { code: ["#7C673A"], color: "Shingle Fawn" },
  { code: ["#63532C"], color: "Dallas" },
  { code: ["#75602C"], color: "Himalaya" },
  { code: ["#545429"], color: "Saragota" },
  { code: ["#636D24"], color: "Fizi Green" },
];

export const metal = [
  { code: ["#C97A30"], color: "Bronze" },
  { code: ["#DAB160"], color: "Equator" },
  { code: ["#C69371"], color: "Fallow" },
  { code: ["#D37F5B"], color: "Burning Sand" },
  { code: ["#CE7259"], color: "Japonica" },
];

export const black = [
  { code: ["#000000"], color: "Black" },
  { code: ["#190000"], color: "Eclipse" },
];
