export const Colors = [
  { code: ["#0000FF"], id: "9", color: "Royal Blue" },
  { code: ["#38B0DE"], id: "2", color: "Sky Blue" },
  { code: ["#1575BF"], id: "16", color: "Denim" },
  { code: ["#213E9E"], id: "18", color: "Persian Blue" },
  { code: ["#01447F"], id: "26", color: "Prussian Blue" },
  { code: ["#129CB7"], id: "59", color: "Iris Blue" },
  { code: ["#191970"], id: "83", color: "Midnight Blue" },
  { code: ["#353B5B"], id: "39", color: "Gulf Blue" },
  { code: ["#9bc3eb"], id: "22", color: "Light Sky Blue" },
  { code: ["#FF0000"], id: "1", color: "Red" },
  { code: ["#9D0C2B"], id: "13", color: "Maroon" },
  { code: ["#9A0C29"], id: "24", color: "Carmine" },
  { code: ["#843138"], id: "28", color: "Old Brick" },
  { code: ["#00FF00"], id: "5", color: "Parrot Green" },
  { code: ["#259797"], id: "6", color: "Sea Green" },
  { code: ["#1AB385"], id: "11", color: "Light Green" },
  { code: ["#166032"], id: "17", color: "Crusoe" },
  { code: ["#4F7C33"], id: "50", color: "Green Leaf" },
  { code: ["#218268"], id: "56", color: "Elf Green" },
  { code: ["#66F4C3"], id: "62", color: "Aquamarine" },
  { code: ["#167E65"], id: "72", color: "Deep Sea" },
  { code: ["#1F881F"], id: "75", color: "Spring Green" },
  { code: ["#1B4B35"], id: "81", color: "Country Green" },
  { code: ["#A4EA9D"], id: "41", color: "Granny Smith Apple" },
  { code: ["#C9E589"], id: "64", color: "Sulu" },
  { code: ["#166461"], id: "78", color: "Blue Stone" },
  { code: ["#80A084"], id: "68", color: "Envy" },
  { code: ["#75A87A"], id: "69", color: "Oxley" },
  { code: ["#FFFF00"], id: "19", color: "Lemon" },
  { code: ["#FFEEA3"], id: "29", color: "Cream Brulee" },
  { code: ["#FFC768"], id: "48", color: "Grandis" },
  { code: ["#DAC01A"], id: "71", color: "Sunflower" },
  { code: ["#FFFF99"], id: "73", color: "Canary" },
  { code: ["#FFD67B"], id: "84", color: "Salomie" },
  { code: ["#FF5900"], id: "14", color: "Dark Orange" },
  { code: ["#FF8C00"], id: "2", color: "Light Orange" },
  { code: ["#FFFFFF"], id: "7", color: "White" },
  { code: ["#F4EFE0"], id: "79", color: "Bianca" },
  { code: ["#E30B5C"], id: "3", color: "Pink" },
  { code: ["#F4869A"], id: "30", color: "Wewak" },
  { code: ["#AA3365"], id: "31", color: "Lipstick" },
  { code: ["#FFC1E4"], id: "43", color: "Cotton Candy" },
  { code: ["#CD526C"], id: "46", color: "Cabaret" },
  { code: ["#D671AC"], id: "38", color: "Pale Violet Red" },
  { code: ["#FFA38C"], id: "49", color: "Mona Lisa" },
  { code: ["#F7AFBF"], id: "58", color: "Cupid" },
  { code: ["#BF5D7A"], id: "65", color: "Royal Heath" },
  { code: ["#B23971"], id: "67", color: "Rouge" },
  { code: ["#DE3163"], id: "82", color: "Cerise" },
  { code: ["#E54D5C"], id: "15", color: "Gajri" },
  { code: ["#C45655"], id: "88", color: "Fuzzy Wuzzy Brown" },
  { code: ["#E56D75"], id: "89", color: "Froly" },
  { code: ["#FEAB9A"], id: "35", color: "Rose Bud" },
  { code: ["#821762"], id: "21", color: "Dark Purple" },
  { code: ["#A42AAA"], id: "23", color: "Dark Orchid" },
  { code: ["#AD0082"], id: "25", color: "Egg Plant" },
  { code: ["#88078E"], id: "77", color: "Dark Violet Purple" },
  { code: ["#6A1F44"], id: "85", color: "Pampadour" },
  { code: ["#633477"], id: "55", color: "Kingfisher Daisy" },
  { code: ["#372D52"], id: "87", color: "Cherry Pie" },
  { code: ["#492293"], id: "51", color: "Persian Indigo" },
  { code: ["#6A4DAF"], id: "36", color: "Blue Marquerite" },
  { code: ["#361556"], id: "57", color: "Christalle" },
  { code: ["#4B2D72"], id: "20", color: "Blue Diamond" },
  { code: ["#FFFDD0"], id: "80", color: "Wheat" },
  { code: ["#DBB985"], id: "10", color: "Raven Gold " },
  { code: ["#FCFAE0"], id: "47", color: "Early Dawn" },
  { code: ["#F1F1C6"], id: "74", color: "Spring Sun" },
  { code: ["#EFD8B6"], id: "66", color: "Champagne" },
  { code: ["#CCB388"], id: "53", color: "Straw" },
  { code: ["#FFF1C6"], id: "34", color: "Blanched Almond" },
  { code: ["#6D7A86"], id: "54", color: "Slate Grey" },
  { code: ["#2E526D"], id: "52", color: "Blumine" },
  { code: ["#5D1F1E"], id: "8", color: "Coke" },
  { code: ["#7F4534"], id: "42", color: "Peanut" },
  { code: ["#8E4D3E"], id: "60", color: "Mule Fawn" },
  { code: ["#74823D"], id: "76", color: "Wasabi" },
  { code: ["#7C673A"], id: "27", color: "Shingle Fawn" },
  { code: ["#63532C"], id: "32", color: "Dallas" },
  { code: ["#75602C"], id: "61", color: "Himalaya" },
  { code: ["#545429"], id: "63", color: "Saratoga" },
  { code: ["#636D24"], id: "44", color: "Fizi Green" },
  { code: ["#C97A30"], id: "33", color: "Bronze" },
  { code: ["#DAB160"], id: "37", color: "Equator" },
  { code: ["#C69371"], id: "40", color: "Fallow" },
  { code: ["#D37F5B"], id: "45", color: "Burning Sand" },
  { code: ["#CE7259"], id: "70", color: "Japonica" },
  { code: ["#000000"], id: "4", color: "Black" },
  { code: ["#190000"], id: "86", color: "Eclipse" },
];

export const blue = [
  { code: ["#0000FF"], id: "9", color: "Royal Blue" },
  { code: ["#38B0DE"], id: "2", color: "Sky Blue" },
  { code: ["#1575BF"], id: "16", color: "Denim" },
  { code: ["#213E9E"], id: "18", color: "Persian Blue" },
  { code: ["#01447F"], id: "26", color: "Prussian Blue" },
  { code: ["#129CB7"], id: "59", color: "Iris Blue" },
  { code: ["#191970"], id: "83", color: "Midnight Blue" },
  { code: ["#353B5B"], id: "39", color: "Gulf Blue" },
  { code: ["#9bc3eb"], id: "22", color: "Light Sky Blue" },
];
export const red = [
  { code: ["#FF0000"], id: "1", color: "Red" },
  { code: ["#9D0C2B"], id: "13", color: "Maroon" },
  { code: ["#9A0C29"], id: "24", color: "Carmine" },
  { code: ["#843138"], id: "28", color: "Old Brick" },
];
export const green = [
  { code: ["#00FF00"], id: "5", color: "Parrot Green" },
  { code: ["#259797"], id: "6", color: "Sea Green" },
  { code: ["#1AB385"], id: "11", color: "Light Green" },
  { code: ["#166032"], id: "17", color: "Crusoe" },
  { code: ["#4F7C33"], id: "50", color: "Green Leaf" },
  { code: ["#218268"], id: "56", color: "Elf Green" },
  { code: ["#66F4C3"], id: "62", color: "Aquamarine" },
  { code: ["#167E65"], id: "72", color: "Deep Sea" },
  { code: ["#1F881F"], id: "75", color: "Spring Green" },
  { code: ["#1B4B35"], id: "81", color: "Country Green" },
  { code: ["#A4EA9D"], id: "41", color: "Granny Smith Apple" },
  { code: ["#C9E589"], id: "64", color: "Sulu" },
  { code: ["#166461"], id: "78", color: "Blue Stone" },
  { code: ["#80A084"], id: "68", color: "Envy" },
  { code: ["#75A87A"], id: "69", color: "Oxley" },
];

export const yellow = [
  { code: ["#FFFF00"], id: "19", color: "Lemon" },
  { code: ["#FFEEA3"], id: "29", color: "Cream Brulee" },
  { code: ["#FFC768"], id: "48", color: "Grandis" },
  { code: ["#DAC01A"], id: "71", color: "Sunflower" },
  { code: ["#FFFF99"], id: "73", color: "Canary" },
  { code: ["#FFD67B"], id: "84", color: "Salomie" },
];
export const orange = [
  { code: ["#FF5900"], id: "14", color: "Dark Orange" },
  { code: ["#FF8C00"], id: "2", color: "Light Orange" },
];
export const white = [
  { code: ["#FFFFFF"], id: "7", color: "White" },
  { code: ["#F4EFE0"], id: "79", color: "Bianca" },
];

export const pink = [
  { code: ["#E30B5C"], id: "3", color: "Pink" },
  { code: ["#F4869A"], id: "30", color: "Wewak" },
  { code: ["#AA3365"], id: "31", color: "Lipstick" },
  { code: ["#FFC1E4"], id: "43", color: "Cotton Candy" },
  { code: ["#CD526C"], id: "46", color: "Cabaret" },
  { code: ["#D671AC"], id: "38", color: "Pale Violet Red" },
  { code: ["#FFA38C"], id: "49", color: "Mona Lisa" },
  { code: ["#F7AFBF"], id: "58", color: "Cupid" },
  { code: ["#BF5D7A"], id: "65", color: "Royal Heath" },
  { code: ["#B23971"], id: "67", color: "Rouge" },
  { code: ["#DE3163"], id: "82", color: "Cerise" },
];

export const gajri = [
  { code: ["#E54D5C"], id: "15", color: "Gajri" },
  { code: ["#C45655"], id: "88", color: "Fuzzy Wuzzy Brown" },
  { code: ["#E56D75"], id: "89", color: "Froly" },
  { code: ["#FEAB9A"], id: "35", color: "Rose Bud" },
];

export const purple = [
  { code: ["#821762"], id: "21", color: "Dark Purple" },
  { code: ["#A42AAA"], id: "23", color: "Dark Orchid" },
  { code: ["#AD0082"], id: "25", color: "Egg Plant" },
  { code: ["#88078E"], id: "77", color: "Dark Violet Purple" },
  { code: ["#6A1F44"], id: "85", color: "Pampadour" },
  { code: ["#633477"], id: "55", color: "Kingfisher Daisy" },
  { code: ["#372D52"], id: "87", color: "Cherry Pie" },
  { code: ["#492293"], id: "51", color: "Persian Indigo" },
  { code: ["#6A4DAF"], id: "36", color: "Blue Marquerite" },
  { code: ["#361556"], id: "57", color: "Christalle" },
  { code: ["#4B2D72"], id: "20", color: "Blue Diamond" },
];

export const cream = [
  { code: ["#FFFDD0"], id: "80", color: "Wheat" },
  { code: ["#DBB985"], id: "10", color: "Raven Gold " },
  { code: ["#FCFAE0"], id: "47", color: "Early Dawn" },
  { code: ["#F1F1C6"], id: "74", color: "Spring Sun" },
  { code: ["#EFD8B6"], id: "66", color: "Champagne" },
  { code: ["#CCB388"], id: "53", color: "Straw" },
  { code: ["#FFF1C6"], id: "34", color: "Blanched Almond" },
];

export const grey = [
  { code: ["#6D7A86"], id: "54", color: "Slate Grey" },
  { code: ["#2E526D"], id: "52", color: "Blumine" },
];

export const brown = [
  { code: ["#5D1F1E"], id: "8", color: "Coke" },
  { code: ["#7F4534"], id: "42", color: "Peanut" },
  { code: ["#8E4D3E"], id: "60", color: "Mule Fawn" },
];

export const mehendi = [
  { code: ["#74823D"], id: "76", color: "Wasabi" },
  { code: ["#7C673A"], id: "27", color: "Shingle Fawn" },
  { code: ["#63532C"], id: "32", color: "Dallas" },
  { code: ["#75602C"], id: "61", color: "Himalaya" },
  { code: ["#545429"], id: "63", color: "Saratoga" },
  { code: ["#636D24"], id: "44", color: "Fizi Green" },
];

export const metal = [
  { code: ["#C97A30"], id: "33", color: "Bronze" },
  { code: ["#DAB160"], id: "37", color: "Equator" },
  { code: ["#C69371"], id: "40", color: "Fallow" },
  { code: ["#D37F5B"], id: "45", color: "Burning Sand" },
  { code: ["#CE7259"], id: "70", color: "Japonica" },
];

export const black = [
  { code: ["#000000"], id: "4", color: "Black" },
  { code: ["#190000"], id: "86", color: "Eclipse" },
];
